In [1]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA


from sklearn import model_selection
import sklearn.metrics as metrics
import numpy as np

In [2]:
data=load_iris()
iris_y=data.target
iris_x=data.data

In [3]:
iris_y.shape, iris_x.shape, type(iris_y), type(iris_x)

((150,), (150, 4), numpy.ndarray, numpy.ndarray)

In [4]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
np.unique(iris_y)

array([0, 1, 2])

In [7]:
pca=PCA(n_components=2)
reduced_x=pca.fit_transform(iris_x)

In [8]:
reduced_x.shape

(150, 2)

In [9]:
X_train,X_test,y_train,y_test=model_selection.train_test_split(reduced_x,iris_y,random_state=1,test_size=0.3)

In [10]:
X_train.shape

(105, 2)

In [11]:
y_train.ravel()

array([2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 2, 0,
       2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0,
       0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 2,
       2, 0, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 1, 2, 0])

In [13]:
from sklearn import svm
classifier=svm.SVC(kernel='rbf')
classifier.fit(X_train,y_train.ravel())
y_predict = classifier.predict(X_test)

In [16]:
print(metrics.precision_score(y_test,y_predict,average=None))
print(metrics.recall_score(y_test,y_predict,average=None))
print(metrics.f1_score(y_test,y_predict,average=None))

[1.         1.         0.92857143]
[1.         0.94444444 1.        ]
[1.         0.97142857 0.96296296]


In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, p=2)
knn.fit(X_train, y_train)

y_predict = knn.predict(X_test)

In [18]:
print(metrics.precision_score(y_test,y_predict,average=None))
print(metrics.recall_score(y_test,y_predict,average=None))
print(metrics.f1_score(y_test,y_predict,average=None))

[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis(n_components=4)
clf.fit(X_train, y_train)

y_predict = clf.predict(X_test)

ValueError: n_components cannot be larger than min(n_features, n_classes - 1).

In [54]:
print(metrics.precision_score(y_test,y_predict,average=None))
print(metrics.recall_score(y_test,y_predict,average=None))
print(metrics.f1_score(y_test,y_predict,average=None))

[1.         1.         0.92857143]
[1.         0.94444444 1.        ]
[1.         0.97142857 0.96296296]


In [55]:
print(clf.n_components)

-1
